name: Build and Run Docker Container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build the Docker image
      run: |
        docker build -t my-docker-image .

    - name: Run the Docker container
      run: |
        docker run my-docker-image
